LanguageCode= "en-US"
Title= "NETED"
paginate = 5
DisqusShortname = ""
Copyright = "All rights reserved - 2016"
canonifyurls = true
theme = "hugo-theme-air"

[author]
  name = "Foxtrot"

[permalinks]
    post = "/post/:year/:month/:day/:slug"

[params]
  description = "This is a website created to help students and people interest in computer networking."
  cover = "images/user.jpeg"
  author = "Foxtrot"
  authorlocation = ""
  authorwebsite = "https://syui.cf/hugo-theme-air"
  bio= "my bio"
  logo = "images/user.jpeg"
  googleAnalyticsUserID = ""
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = ""
  githubName = "Foxtrot"
  twitterName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = true
  mainSections = ["post"]