LanguageCode= "en-US"
Title= "NETED"
paginate = 3
DisqusShortname = "neted."
Copyright = "All rights reserved - 2020"
canonifyurls = true
theme = "hugo-theme-air"

[author]
  name = "Foxtrot"

[permalinks]
    post = "/post/:year/:month/:day/:slug"

[params]
  description = "This is a website made to help students and people interest in computer network to solve their problems and teach what is neccessary to be success in the IT field"
  cover = "images/user.jpeg"
  author = "Foxtrot"
  logo = ""
  googleAnalyticsUserID = ""
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = ""
  githubName = "indiafoxtrot"
  twitterName = "RexFoxtrot"
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = true
  mainSections = ["post"]