BaseUrl= "https://www.neted.network"
LanguageCode= "en-US"
Title= "NETE"
paginate = 5
DisqusShortname = ""
Copyright = "All rights reserved - 2020"
canonifyurls = true

[author]
  name = "rexfoxtrot"

[permalinks]
    post = "/post/:year/:month/:day/:slug"

[params]
  description = "This is a website helps students and people interest in computer network to solve their problems and teach exciting what is neccessary to nail your IT  carrier"
  cover = "images/user.jpeg"
  author = "rexfoxtrot"
  bio= "my bio"
  logo = "images/user.png"
  googleAnalyticsUserID = ""
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = ""
  githubName = "rexfoxtrot"
  twitterName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = true
  mainSections = ["post"]
